<title>Supir Truk</title>
<div class="container">
    <div class="card mt-5">
        <div class="card-header text-center" style="background-color:#343A40; color: #FFFFFF;">
            <strong>EDIT DATA</strong>
        </div>
        <div class="card-header">

            <a href="/supirtruk" class="btn btn-secondary">Kembali</a>
        </div>
        <div class="card-body">

            <form autocomplete="off" method="post" action="/supirtruk/update/<?php echo $supir->id_supir ?>">
                <div class="form-group">
                    <label>Nama Pemilik</label>
                    <select class="form-control" id="id_pemilik" name="id_pemilik">
                    <option value="<?php echo $supir->pemilik->id_pemilik ?>"><?php echo $supir->pemilik->nama_pemilik ?></option>
                    <?php foreach ($pemilik as $p) { ?>
                        <option value="<?php echo $p->id_pemilik ?>"><?php echo $p->nama_pemilik ?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="form-group">
                    <label>Nama Supir</label>
                    <input type="text" autocomplete="off" name="nama_supir" class="form-control" placeholder="Nama Supir" value="<?php echo $supir->nama_supir ?>">
                </div>

                <div class="form-group">
                    <label>Nopol</label>
                    <input type="text" autocomplete="off" name="nopol" class="form-control" placeholder="Nopol" value="<?php echo $supir->nopol ?>">
                </div>


                <div class="form-group">
                    <input type="submit" class="btn btn-success" value="Simpan">
                </div>


            </form>

        </div>
    </div>
</div>