<title>Supir Truk</title>
<div class="container">
    <div class="card mt-5">
        <div class="card-header text-center" style="background-color:#343A40; color: #FFFFFF;">
            <strong>TAMBAH DATA</strong>
        </div>
        <div class="card-header">

            <a href="/supirtruk" class="btn btn-secondary">Kembali</a>
        </div>
        <div class="card-body">
<!-- 
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li> {{$error}} </li>
                    @endforeach
                </ul>
            </div>
            @endif -->
            <form method="post" action="/supirtruk/proses">
                <div class="form-group">
                    <label>Nama Pemilik</label>
                    <select class="form-control" id="id_pemilik" name="id_pemilik">
                        <option value="" disabled selected>Nama Pemilik</option>
                        <?php foreach ($pemilik as $p) { ?>
                        <option value="<?php echo $p->id_pemilik ?>"><?php echo $p->nama_pemilik ?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="form-group">
                    <label>Nama Supir</label>
                    <input type="text" name="nama_supir" autocomplete="off" class="form-control" placeholder="Nama Supir">
                </div>

                <div class="form-group">
                    <label>Nopol</label>
                    <input type="text" name="nopol" autocomplete="off" class="form-control" placeholder="Nopol">
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-success" value="Simpan">
                </div>

            </form>

        </div>
    </div>
</div>